on:
  workflow_call:
    inputs:
      node-version:
        default: 22
        description: The version of node to set up
        type: number
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup Environment
    steps:
      - name: Check formatting
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build